INSERT INTO [dbo].[CoffeesDrunk]([Date], [User], [Coffee]) VALUES ('2020-01-01','peter','capuccino');
INSERT INTO [dbo].[CoffeesDrunk]([Date], [User], [Coffee]) VALUES ('2020-01-02','peter','mocha');
INSERT INTO [dbo].[CoffeesDrunk]([Date], [User], [Coffee]) VALUES ('2020-01-03','peter','capuccino');
INSERT INTO [dbo].[CoffeesDrunk]([Date], [User], [Coffee]) VALUES ('2020-01-03','peter','espresso');
INSERT INTO [dbo].[CoffeesDrunk]([Date], [User], [Coffee]) VALUES ('2020-01-03','peter','capuccino');
INSERT INTO [dbo].[CoffeesDrunk]([Date], [User], [Coffee]) VALUES ('2020-01-04','peter','capuccino');
INSERT INTO [dbo].[CoffeesDrunk]([Date], [User], [Coffee]) VALUES ('2020-01-04','peter','capuccino');
INSERT INTO [dbo].[CoffeesDrunk]([Date], [User], [Coffee]) VALUES ('2020-01-05','peter','capuccino');
INSERT INTO [dbo].[CoffeesDrunk]([Date], [User], [Coffee]) VALUES ('2020-01-05','peter','espresso');
INSERT INTO [dbo].[CoffeesDrunk]([Date], [User], [Coffee]) VALUES ('2020-01-01','damian','black');
INSERT INTO [dbo].[CoffeesDrunk]([Date], [User], [Coffee]) VALUES ('2020-01-01','damian','espresso');
INSERT INTO [dbo].[CoffeesDrunk]([Date], [User], [Coffee]) VALUES ('2020-01-01','damian','flat white');
INSERT INTO [dbo].[CoffeesDrunk]([Date], [User], [Coffee]) VALUES ('2020-01-02','damian','espresso');
INSERT INTO [dbo].[CoffeesDrunk]([Date], [User], [Coffee]) VALUES ('2020-01-03','damian','espresso');
INSERT INTO [dbo].[CoffeesDrunk]([Date], [User], [Coffee]) VALUES ('2020-01-04','damian','long black');
INSERT INTO [dbo].[CoffeesDrunk]([Date], [User], [Coffee]) VALUES ('2020-01-05','damian','espresso');
INSERT INTO [dbo].[CoffeesDrunk]([Date], [User], [Coffee]) VALUES ('2020-01-05','damian','capuccino');
INSERT INTO [dbo].[CoffeesDrunk]([Date], [User], [Coffee]) VALUES ('2020-01-06','peter','capuccino');
INSERT INTO [dbo].[CoffeesDrunk]([Date], [User], [Coffee]) VALUES ('2020-01-06','peter','capuccino');
INSERT INTO [dbo].[CoffeesDrunk]([Date], [User], [Coffee]) VALUES ('2020-01-07','peter','long black');
INSERT INTO [dbo].[CoffeesDrunk]([Date], [User], [Coffee]) VALUES ('2020-01-08','peter','long black');
INSERT INTO [dbo].[CoffeesDrunk]([Date], [User], [Coffee]) VALUES ('2020-01-09','peter','capuccino');
INSERT INTO [dbo].[CoffeesDrunk]([Date], [User], [Coffee]) VALUES ('2020-01-10','damian','capuccino');
