version: '3'
services:
  sqlserver1:
    build: 
      context: .
      image: azure-sql-edge:latest
      dockerfile: dockerfile
    ports:  
      - "15789:1433"
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer 
      - MSSQL_SA_PASSWORD=order21
      - MSSQL_DATA_DIR=/var/opt/sqlserver/data
      - MSSQL_LOG_DIR=/var/opt/sqlserver/log
      - MSSQL_BACKUP_DIR=/var/opt/sqlserver/backup
    volumes: 
      - sqlsystem:/work/mssql/
      - sqldata:/work/sqlserver/data
      - sqllog:/work/sqlserver/log
      - sqlbackup:/work/sqlserver/backup
volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup:
